//! Legacy VFS bridge — presents the SemanticVectorStore as a POSIX filesystem.
//!
//! How it works:
//!   • A trie maps UTF-8 path components to `VectorId`s.
//!   • `open("/data/reports/q4.csv")` resolves through the trie and returns
//!     the payload bytes from the associated `SemanticVector`.
//!   • `readdir` enumerates all trie children at a given path prefix.
//!   • `semantic_open(query_embedding, k)` returns the k nearest vectors as
//!     virtual "files", letting AI agents address data by meaning rather than
//!     location.
//!   • Writes are passed back into `VectorStore::insert` (with a new
//!     embedding generated by the Scheduler's embedding model).

use hashbrown::HashMap;
use crate::vector::{SemanticNamespace, VectorId, VectorStore};

// ---------------------------------------------------------------------------
// VfsNode — a node in the path trie
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum VfsNodeKind {
    Directory,
    File,
    /// A virtual file backed by a cluster-remote RDMA reference.
    RemoteRef,
}

#[derive(Clone, Debug)]
pub struct VfsNode {
    pub name:     String,
    pub kind:     VfsNodeKind,
    /// Points into the VectorStore; `None` for pure-directory nodes.
    pub vector_id: Option<VectorId>,
    pub ns:        SemanticNamespace,
    children:      HashMap<String, VfsNode>,
}

impl VfsNode {
    pub fn directory(name: impl Into<String>, ns: SemanticNamespace) -> Self {
        Self {
            name: name.into(),
            kind: VfsNodeKind::Directory,
            vector_id: None,
            ns,
            children: HashMap::new(),
        }
    }

    pub fn file(name: impl Into<String>, ns: SemanticNamespace, id: VectorId) -> Self {
        Self {
            name: name.into(),
            kind: VfsNodeKind::File,
            vector_id: Some(id),
            ns,
            children: HashMap::new(),
        }
    }

    pub fn insert_child(&mut self, node: VfsNode) {
        self.children.insert(node.name.clone(), node);
    }

    pub fn get_child(&self, name: &str) -> Option<&VfsNode> {
        self.children.get(name)
    }

    pub fn list_children(&self) -> impl Iterator<Item = &VfsNode> {
        self.children.values()
    }
}

// ---------------------------------------------------------------------------
// VfsBridge — the actual bridge between the trie and VectorStore
// ---------------------------------------------------------------------------

pub struct VfsBridge {
    root: VfsNode,
}

impl VfsBridge {
    pub fn new() -> Self {
        Self {
            root: VfsNode::directory("/", SemanticNamespace::SYSTEM),
        }
    }

    /// Register a path → VectorId mapping.
    ///
    /// Intermediate directory nodes are created automatically.
    pub fn bind(&mut self, path: &str, id: VectorId, ns: SemanticNamespace) {
        let components: Vec<&str> = path.trim_start_matches('/').split('/').collect();
        let mut node = &mut self.root;
        let last = components.len() - 1;
        for (i, component) in components.iter().enumerate() {
            if i == last {
                node.insert_child(VfsNode::file(*component, ns, id));
            } else {
                // Create intermediate directory if absent.
                if !node.children.contains_key(*component) {
                    node.insert_child(VfsNode::directory(*component, ns));
                }
                node = node.children.get_mut(*component).unwrap();
            }
        }
    }

    /// Resolve a path to a `VfsNode`.
    pub fn resolve<'a>(&'a self, path: &str) -> Option<&'a VfsNode> {
        if path == "/" {
            return Some(&self.root);
        }
        let mut node = &self.root;
        for component in path.trim_start_matches('/').split('/') {
            node = node.get_child(component)?;
        }
        Some(node)
    }

    /// POSIX-style `open`: returns the payload bytes from the vector store.
    pub fn open<'a>(
        &'a self,
        path:  &str,
        store: &'a VectorStore,
    ) -> Result<Option<&'a [u8]>, VfsError> {
        let node = self.resolve(path).ok_or(VfsError::NotFound)?;
        match node.kind {
            VfsNodeKind::Directory => Err(VfsError::IsDirectory),
            VfsNodeKind::File | VfsNodeKind::RemoteRef => {
                let id = node.vector_id.ok_or(VfsError::NotFound)?;
                let vec = store.get(id).ok_or(VfsError::StaleRef(id))?;
                Ok(vec.payload.as_deref())
            }
        }
    }

    /// POSIX-style `readdir`: list entries at path.
    pub fn readdir<'a>(&'a self, path: &str) -> Result<Vec<&'a VfsNode>, VfsError> {
        let node = self.resolve(path).ok_or(VfsError::NotFound)?;
        if node.kind != VfsNodeKind::Directory {
            return Err(VfsError::NotDirectory);
        }
        Ok(node.list_children().collect())
    }

    /// Semantic `open`: returns the k nearest VectorIds to a query embedding.
    ///
    /// Results are exposed as virtual path entries under `/semantic/<rank>`.
    pub fn semantic_open(
        &self,
        ns:    SemanticNamespace,
        query: &[f32],
        k:     usize,
        store: &VectorStore,
    ) -> Vec<(String, VectorId, f32)> {
        store.query(ns, query, k)
            .into_iter()
            .enumerate()
            .map(|(rank, (id, score))| (format!("/semantic/{rank}"), id, score))
            .collect()
    }

    /// Write a new file: inserts into VectorStore and binds the path.
    /// The caller is responsible for generating the embedding (e.g., via the Scheduler).
    pub fn write(
        &mut self,
        path:      &str,
        ns:        SemanticNamespace,
        embedding: Vec<f32>,
        payload:   Vec<u8>,
        meta:      HashMap<String, String>,
        store:     &mut VectorStore,
    ) -> VectorId {
        let id = store.insert(ns, embedding, Some(payload), meta);
        self.bind(path, id, ns);
        id
    }
}

// ---------------------------------------------------------------------------
// Error
// ---------------------------------------------------------------------------

#[derive(Debug, thiserror::Error)]
pub enum VfsError {
    #[error("path not found")]
    NotFound,
    #[error("path is a directory")]
    IsDirectory,
    #[error("path is not a directory")]
    NotDirectory,
    #[error("stale vector reference {0:?}")]
    StaleRef(VectorId),
    #[error("permission denied")]
    PermissionDenied,
}
